#!/usr/bin/env bash
sudo rm -rf /home/centos/tribuna-independiente/project
sudo git clone -b master /home/centos/tribuna-independiente/git /home/centos/tribuna-independiente/project
sudo bash -x /home/centos/tribuna-independiente/project/gradle/bash/deploy.sh

